name: Linter
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    


jobs:
  build:
    runs-on: ubuntu-latest
    
    #strategy:
      #matrix:
        #swift versions
   

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Linter
        uses: github/super-linter@v4.9.4    #calling the Super-Linter to scan through code for errors
        env: 
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
